"""add trace_data and receipt_data to transactions

Revision ID: e9414a2d8914
Revises: fb79e1cdcb0f
Create Date: 2026-06-27 11:25:52.066080

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e9414a2d8914"
down_revision: str | Sequence[str] | None = "fb79e1cdcb0f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions", sa.Column("trace_data", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.add_column(
        "transactions", sa.Column("receipt_data", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions", "receipt_data")
    op.drop_column("transactions", "trace_data")
    # ### end Alembic commands ###
