"""initial tables

Revision ID: fb79e1cdcb0f
Revises:
Create Date: 2026-06-27 10:20:01.762010

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fb79e1cdcb0f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blocks",
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("parent_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("timestamp", sa.Integer(), nullable=False),
        sa.Column("gas_used", sa.Integer(), nullable=False),
        sa.Column("gas_limit", sa.Integer(), nullable=False),
        sa.Column("miner", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tx_count", sa.Integer(), nullable=False),
        sa.Column("raw", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("number"),
    )
    op.create_index(op.f("ix_blocks_hash"), "blocks", ["hash"], unique=True)
    op.create_index(op.f("ix_blocks_timestamp"), "blocks", ["timestamp"], unique=False)
    op.create_table(
        "contract_labels",
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("abi", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_token", sa.Integer(), nullable=False),
        sa.Column("is_precompile", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("address"),
    )
    op.create_table(
        "token_metadata",
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("symbol", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("decimals", sa.Integer(), nullable=False),
        sa.Column("currency", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("total_supply", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("logo_uri", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("holder_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("address"),
    )
    op.create_index(op.f("ix_token_metadata_name"), "token_metadata", ["name"], unique=False)
    op.create_table(
        "transfer_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tx_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("block_number", sa.Integer(), nullable=False),
        sa.Column("log_index", sa.Integer(), nullable=False),
        sa.Column("token_addr", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("from_addr", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("to_addr", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("amount", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("timestamp", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transfer_events_block_number"), "transfer_events", ["block_number"], unique=False
    )
    op.create_index(
        op.f("ix_transfer_events_from_addr"), "transfer_events", ["from_addr"], unique=False
    )
    op.create_index(
        op.f("ix_transfer_events_to_addr"), "transfer_events", ["to_addr"], unique=False
    )
    op.create_index(
        op.f("ix_transfer_events_token_addr"), "transfer_events", ["token_addr"], unique=False
    )
    op.create_index(
        op.f("ix_transfer_events_tx_hash"), "transfer_events", ["tx_hash"], unique=False
    )
    op.create_table(
        "transactions",
        sa.Column("hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("block_number", sa.Integer(), nullable=False),
        sa.Column("block_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("from_addr", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("to_addr", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sa.Integer(), nullable=False),
        sa.Column("gas_limit", sa.Integer(), nullable=False),
        sa.Column("gas_used", sa.Integer(), nullable=False),
        sa.Column("gas_price", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("max_fee_per_gas", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("max_priority_fee_per_gas", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("base_fee", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("fee_token", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("fee_amount", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("nonce", sa.Integer(), nullable=False),
        sa.Column("nonce_key", sa.Integer(), nullable=False),
        sa.Column("value", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("chain_id", sa.Integer(), nullable=False),
        sa.Column("tx_type", sa.Integer(), nullable=False),
        sa.Column("input", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("raw", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("timestamp", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["block_number"],
            ["blocks.number"],
        ),
        sa.PrimaryKeyConstraint("hash"),
    )
    op.create_index(
        op.f("ix_transactions_block_number"), "transactions", ["block_number"], unique=False
    )
    op.create_index(op.f("ix_transactions_from_addr"), "transactions", ["from_addr"], unique=False)
    op.create_index(op.f("ix_transactions_timestamp"), "transactions", ["timestamp"], unique=False)
    op.create_index(op.f("ix_transactions_to_addr"), "transactions", ["to_addr"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transactions_to_addr"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_timestamp"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_from_addr"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_block_number"), table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(op.f("ix_transfer_events_tx_hash"), table_name="transfer_events")
    op.drop_index(op.f("ix_transfer_events_token_addr"), table_name="transfer_events")
    op.drop_index(op.f("ix_transfer_events_to_addr"), table_name="transfer_events")
    op.drop_index(op.f("ix_transfer_events_from_addr"), table_name="transfer_events")
    op.drop_index(op.f("ix_transfer_events_block_number"), table_name="transfer_events")
    op.drop_table("transfer_events")
    op.drop_index(op.f("ix_token_metadata_name"), table_name="token_metadata")
    op.drop_table("token_metadata")
    op.drop_table("contract_labels")
    op.drop_index(op.f("ix_blocks_timestamp"), table_name="blocks")
    op.drop_index(op.f("ix_blocks_hash"), table_name="blocks")
    op.drop_table("blocks")
    # ### end Alembic commands ###
